name: Validators

on: push

jobs:
  run:
    name: Run Mass sector generator
    runs-on: ubuntu-latest
    env:
      SECTORS_OUT: $GITHUB_WORKSPACE/test_mass_sector_generator/maps
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Launch Mass Sector Generator Script
        env:
          ZILON_LIV_SCHEME_CATALOG: $GITHUB_WORKSPACE/Zilon.Client/Assets/Resources/Schemes
        run: chmod +x BuildServerScripts/sector_mass_generator.sh && BuildServerScripts/sector_mass_generator.sh
      - uses: actions/upload-artifact@v1
        with:
          name: MassSectorGeneration
          path: $SECTORS_OUT